# This is a basic workflow to help you get started with Actions

name: PR Dependency check

# Controls when the action will run. 
on:
  pull_request_target: 
    types: [opened, edited, closed, reopened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    name: Check Dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Check Dependencies
        uses: gregsdennis/dependencies-action@v1.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
